sudo: required
language: python
python:
- 3.6.6
install:
  - sudo apt-get update
  - pip install -r requirements.txt
script:
  - python -W ignore -m unittest discover
notifications:
    email:
        - lituta@outlook.com
