import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.basic.Answer import Answer

ENDPOINT = 'http://gaiadev01.isi.edu:3030/latest_rpi_en/query'


def run(xml_query):
    with open(xml_query) as f:
        xml = f.read()

    ans = Answer(xml, ENDPOINT).ask()

    print(ans['response'])

# example query provided by NIST
# run('graph_query.xml')

# subgraph as query in our dataset
run('autogenerated_query_3.xml')



