import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.basic.XMLLoader import XMLLoader

ENDPOINT = 'http://gaiadev01.isi.edu:3030/rpi0901aif80d2/query'


def run(xml_query):
    with open(xml_query) as f:
        xml = f.read()

    all_ans = XMLLoader(xml).answer_all(ENDPOINT)

    for ans in all_ans:
        print(ans['sparql'])
        print(ans['response'])

# example query provided by NIST
# run('xml_queries/graph_query.xml')

# subgraph as query in our dataset
# run('xml_queries/autogenerated_query_3.xml')

run('xml_queries/zerohop_test1.xml')

run('xml_queries/simple_query.xml')


