import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.advanced.AdvancedAnswer import AdvancedAnswer

ENDPOINT = 'http://gaiadev01.isi.edu:3030/rpi0901aida9979/query'


def run(xml_query):
    with open(xml_query) as f:
        xml = f.read()

    ans = AdvancedAnswer(xml, ENDPOINT).ask_with_specified_relaxation({'wider_range': True})

    print(ans['sparql'])
    print(ans['response'])

# example query provided by NIST
# run('graph_query.xml')

# subgraph as query in our dataset
run('autogenerated_query_1.xml')



