import sys
sys.path.append('..')


from src.basic.Question import Question
from src.basic.Answer import Answer


xml_query = 'autogenerated_query_1.xml'
# xml_query = 'graph_query.xml'
with open(xml_query) as f:
    xml = f.read()


q = Question(xml).serialize_strict_sparql()

ans = Answer(Question(xml))

print(ans.ask())
