import sys
sys.path.append('..')


from src.advanced.AdvancedQuestion import AdvancedQuestion
# from src.basic.Answer import Answer


def run(xml_query):
    with open(xml_query) as f:
        xml = f.read()

    # ans = Answer(Question(xml)).ask()

    q = AdvancedQuestion(xml)
    q.test()

# example query provided by NIST
run('graph_query.xml')

# subgraph as query in our dataset
# run('autogenerated_query_1.xml')



