import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.advanced.AdvancedAnswer import AdvancedAnswer

ENDPOINT = 'http://gaiadev01.isi.edu:3030/rpi0901aif80d2/query'


def run(xml_query):
    with open(xml_query) as f:
        xml = f.read()

    ans = AdvancedAnswer(xml, ENDPOINT).ask({'wider_range': False, 'at_least_n': 0, 'on_supergraph': True,
                                             'ignore_enttype': False})

    print(ans['sparql'])
    print(ans['response'])

# example query provided by NIST
# run('graph_query.xml')

# subgraph as query in our dataset
run('outputs/autogenerated_query_2.xml')

# run('simple_query.xml')


