
from src.basic.utils import *

FILTER_OPERATOR = {
    AIDA_STARTOFFSET: '<=',
    AIDA_ENDOFFSETINCLUSIVE: '>=',
    AIDA_BOUNDINGBOXUPPERLEFTX: '<=',
    AIDA_BOUNDINGBOXUPPERLEFTY: '<=',
    AIDA_BOUNDINGBOXLOWERRIGHTX: '>=',
    AIDA_BOUNDINGBOXLOWERRIGHTY: '>='
}

